---
- name: Install PHP and required extensions
  yum:
    name: "{{ php_pkgs }}"
    state: present
    disable_excludes: all

- name: Upload php.ini
  copy:
    src: php.ini
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0644